name: Weekly GitHub Trending Post

on:
  schedule:
    # 매주 일요일 오전 2시(KST)에 실행 (UTC 토요일 17:00)
    - cron: '0 17 * * 6'
  workflow_dispatch: # 수동 실행 가능

jobs:
  create-trending-post:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Weekly Trending Post
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            안녕하세요! 이번 주 GitHub Trending 블로그 포스트를 작성해주세요.

            ## 요구사항

            1. **데이터 수집**
               - https://github.com/trending?since=weekly 페이지에서 트렌딩 레포지토리 정보를 수집합니다.
               - 각 레포지토리의 상세 페이지와 README를 확인하여 내용을 파악합니다.

            2. **필터링 기준**
               - 신기술이나 많은 사람들이 궁금해할 만한 내용이 아니면 제외합니다.
               - 겉만 번지르르하고 실질적 가치가 없는 프로젝트는 제외합니다.
               - 최종적으로 5-10개 정도의 의미있는 레포지토리만 선별합니다.

            3. **Jekyll 포스트 작성**
               - 파일 위치: `_posts/YYYY-MM-DD-github-trending-week-N.md`
               - 파일명 형식: 오늘 날짜를 사용하여 `2025-10-22-github-trending-week-43.md` 형식
               - 반드시 한국어로 작성합니다.
               - 이모지는 전문성이 떨어지므로 사용하지 않습니다.

            4. **Jekyll 헤더 형식**
            ```yaml
            ---
            title: YYYY년 MM월 N주차 GitHub Trending
            description: [이번 주 트렌딩의 핵심 주제나 특징을 한 문장으로]
            author: claude
            date: 'YYYY-MM-DD HH:MM:SS'
            categories:
              - GitHub Trending
            tags:
              - Coding
              - dev
              - [관련 기술 태그들]
            pin: false
            math: false
            mermaid: false
            image:
              path: "/media/YYYY-MM-DD-github-trending/thumbnail.png"
            ---
            ```

            5. **본문 구조**
               - 간단한 도입부 (2-3문장)
               - 각 레포지토리별로:
                 * H2 헤더 (## 레포지토리명)
                 * 대표 이미지 (README에서 가장 적절한 이미지 선택 또는 레포지토리 소셜 이미지)
                 * GitHub 링크
                 * 핵심 내용 요약 (3-5문단, 중요한 내용 위주)
               - 마무리 멘트

            6. **작성 가이드**
               - 요약은 기술적으로 정확하고 구체적이어야 합니다.
               - 단순 번역이 아닌, 이해하기 쉬운 설명으로 작성합니다.
               - 각 레포지토리의 실질적 가치와 활용 사례를 포함합니다.
               - 코드 예제가 있으면 간단히 포함합니다.

            7. **이미지 처리**
               - 각 레포지토리의 대표 이미지 URL을 확인합니다.
               - 이미지는 마크다운 형식으로 삽입: `![이미지설명](이미지URL)`
               - 이미지가 없는 경우 생략 가능합니다.

            8. **커밋 및 푸시**
               - 작성한 포스트 파일을 git add 합니다.
               - 커밋 메시지: "Add GitHub Trending post for week [N] of [Month] [Year]"
               - main 브랜치에 직접 푸시합니다.

            작업을 시작해주세요!

          claude_args: '--allowed-tools "Bash(git:*)" --allowed-tools "WebFetch"'

      - name: Verify Post Created
        run: |
          if [ -n "$(git log -1 --pretty=format:%s | grep 'GitHub Trending')" ]; then
            echo "✅ Weekly trending post created successfully!"
          else
            echo "❌ Failed to create weekly trending post"
            exit 1
          fi
